apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mrmpg-admin
  labels:
    app: mrmpg-admin
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mrmpg-admin
  template:
    metadata:
      labels:
        app: mrmpg-admin
    spec:
      containers:
        - name: mrmpg-admin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
