apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mrmpg-backend
  labels:
    app: mrmpg-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mrmpg-backend
  template:
    metadata:
      labels:
        app: mrmpg-backend
    spec:
      containers:
        - name: mrmpg-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
