replicaCount: 2

image:
  repository: mrmpg-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

env:
  NODE_ENV: production
  PORT: "5000"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 512Mi
